### ISSUE TITLE
Unload function

### ISSUE THREAD

**Issue by eXCoreX** [EquiFox/KsDumper#1]
https://github.com/EquiFox/KsDumper/blob/master/KsDumperDriver/Driver.c#L100

function signature should be with NTSTATUS return val (not required to return something actually). 

Also:
https://github.com/EquiFox/KsDumper/blob/master/KsDumperDriver/Driver.c#L105

It's better make the symLink global and you are deleting wrong link anyway, it should be the one with `"Dos"` in the name. If have time, i'll make a pull request.

**Comment by EquiFox** [comment]
Thanks for spotting this one !
My bad, totally missed it.
