### ISSUE TITLE
how to dump EAC games

### ISSUE THREAD

**Issue by FocuzJS** [EquiFox/KsDumper#3]
You could just rename r5apex to eaclauncher and then it would've let you dump with Scylla. Sick job tho with all the work you put into this, im sure you'll improve much with your drivers as you rethink what's possible from kernel ;)

**Comment by EquiFox** [comment]
Yeah, I literally understood that trick 5 mins after pushing this to Github haha.
Anyway, it might help someone learn :)

**Comment by FocuzJS** [comment]
I sure hope it does, I too recently was a victim of the KMDF learning curve as well ;)

**Comment by FocuzJS** [comment]
also do note you should look into clearing capcom traces when working with anti-cheats like EAC, just a suggestion since people [here](https://www.unknowncheats.me/forum/apex-legends/321656-eac-hwid-ban-shared-btw-games.html) are having issues where capcom is the reason people using PI are getting banned.
Specifically `MmUnloadedDrivers` in the case of EAC. The registries are less of a concern. :)

**Comment by eXCoreX** [comment]
I think this is more of a private stuff, what's the point of giving away a finished product in this case?

**Comment by FocuzJS** [comment]
the code is already pasted everywhere. sharing knowledge like this is power
for anyone reading this that's [interested](https://www.unknowncheats.me/forum/anti-cheat-bypass/302508-deleting-entry-mmunloadeddrive.html), that's the correct way of doing so if you're not using a bug like empty driver name ;)

**Comment by 2sad32** [comment]
> код уже наклеен везде. делиться такими знаниями-это власть
> для тех, кто читает это, что [интересно ](https://www.unknowncheats.me/forum/anti-cheat-bypass/302508-deleting-entry-mmunloadeddrive.html), это правильный способ сделать это, если вы не используете ошибку, такую как пустое имя драйвера ;)

You can try league dumper, with UAC disabled, or at the boot input .
