### ISSUE TITLE
BSOD when loading driver

### ISSUE THREAD

**Issue by Whitesun123** [EquiFox/KsDumper#8]
Hello, so when I try to load the drivers I just get a BSOD.

![Capture](https://user-images.githubusercontent.com/41925432/107871967-aa8e2180-6ea6-11eb-8d80-b330b4bd79d3.PNG)

When loading Capcom.sys it works but when I try to then load KsDumperDriver.sys I just blue screen.
I have disabled Hyper-V, Credential Guard and Device Guard.

**Comment by advokat11** [comment]
how you fixed this?

**Comment by quanmanss11** [comment]
restart pc and load ksdumperdirver.sys ? (idk)

**Comment by quanmanss11** [comment]
try restart your pc and load the driver

**Comment by Whitesun123** [comment]
> 

My friend this is almost 2 years old haha but I managed to fix it a long time ago by using a different  driver loader
